spring:
  banner:
    image:
      location: classpath:/banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/rest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  main:
    allow-circular-references: true
  flyway:
    locations:
      - classpath:db/migration
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false
server:
  port: 80

